version: '3.3'
networks:
  app_net_foor:
    ipam:
      config:
        - subnet: 10.0.4.0/24
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      app_net_foor:
        ipv4_address: 10.0.4.10
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db
    networks:
      app_net_foor:
        ipv4_address: 10.0.4.20

volumes:
  redis_data:
  redisinsight_data:
