version: '3.3'
networks:
  app_net_three:
    ipam:
      config:
        - subnet: 10.0.3.0/24
services:
  postgres:
    image: postgres:11.6
    container_name: my-postgres
    user: root
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net_three:
        ipv4_address: 10.0.3.10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      app_net_three:
        ipv4_address: 10.0.3.20

volumes:
  postgres_data:
  pgadmin_data: