# Use root/example as user/password credentials
version: '3'
networks:
  app_net_one:
    ipam:
      config:
        - subnet: 10.0.1.0/24
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      app_net_one:
        ipv4_address: 10.0.1.10

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
    networks:
      app_net_one:
        ipv4_address: 10.0.1.20
